### ISSUE TITLE
add major cities names function

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/vizstorm-GIF#70]

**Comment by aappling-usgs** [comment]
Here's what I can achieve with the current setup and the viz_config.yml chunk that follows:

![animation_a](https://user-images.githubusercontent.com/12039957/44536581-cf84ed80-a6ca-11e8-8923-96c7cb433495.gif)

```yml
cities:
  dot: # parameters for general coloring of the
    bg: "gray30"
    col: NA
    pch: 21
    cex: 1.1
  text:
    col: "gray30"
    font: 1
    cex: 1.1
    angle: 30 # angle in radians for position of label relative to dot. pos is computed from angle: 225-315=1, 315-45=4, 45-135=3, 135-225=2
    dist: 0.01 # relative (fraction of window width) distance from dot to label
  pop_min: 500000 # minimum population size of cities to be chosen by default; `custom` will make additions or modifications and `exclude` will make subtractions
  custom: # cities to add or modify relative to the maps::us.cities dataset. added cities can use lat/long from us.cities if they are present in us.cities, even if they don't meet the pop_min criterion
    -
      name: "Houston TX"
    -
      name: "Fort Worth TX"
      text_angle: 150
    -
      name: "Dallas TX"
    -
      name: "Memphis TN"
    -
      name: "San Antonio TX"
      text_angle: -180
    -
      name: "Austin TX"
      text_angle: -180
    -
      name: "Corpus Christi TX"
      dot_cex: 0.8
      text_cex: 0.8
      text_angle: -45
    -
      name: "Port Aransas TX"
      pop: 3480
      lat: 27.8333
      long: -97.0667
      dot_cex: 0.8
      text_cex: 0.8
      text_angle: 0
    -
      name: "Conroe TX"
      dot_cex: 0.8
      text_cex: 0.8
      text_angle: 170
    -
      name: "Nederland TX"
      pop: 17547
      lat: 29.973056
      long: -93.9967
      dot_cex: 0.8
      text_cex: 0.8
    -
      name: "Port Lavaca TX"
      pop: 12248
      lat: 28.6156
      long: -96.6297
      dot_cex: 0.8
      text_cex: 0.8
      text_angle: 0
    -
      name: "Rockport TX"
      pop: 8766
      lat: 28.0486
      long: -97.0411
      dot_cex: 0.8
      text_cex: 0.8
    -
      name: "Victoria TX"
      pop: 62592
      lat: 28.8169
      long: -96.9933
      dot_cex: 0.8
      text_cex: 0.8
      text_angle: 180
  exclude:
    - "Jacksonville FL"
    - "Oklahoma City OK"
```

Key features:
1) Major cities will be automatically selected from `maps::us.cities` with the `pop_min` threshold
2) Exclude any selected cities by listing them under `exclude`
3) Add cities by listing them under `custom`. if you add a city that's available in `maps::us.cities`, all you need to provide is the city `name`. if you add a city that's outside that database, you need to provide `lat` and `lon` (`pop` is optional)
4) Customize the positioning or formatting of cities by specifying `dot_cex`, `text_angle`, etc. under `custom`. Any city that's selected by the pop_min filtering in (1), or added manually in (3), can be mentioned and styled in the `custom` block.
