### ISSUE TITLE
add ocean names function

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/vizstorm-GIF#71]

**Comment by jzwart** [comment]
![image](https://user-images.githubusercontent.com/4825431/42706931-19b9825a-869e-11e8-9d9b-1466bdad6c73.png)

**Comment by aappling-usgs** [comment]
Looking pretty good as of #93, but let's also work with the yaml format just a little bit so it can be
```yml
ocean_name_placement:
 g_of_mex:
   x1: 0.05
   y1: 0.70
   label: 'Gulf of Mexico'
```

**Comment by jread-usgs** [comment]
Maybe even take things one step further w/ the yaml to simplify it:
```yaml
  ocean_name_placement:
    -
      x1: 0.05
      y1: 0.70
      label: 'Gulf of Mexico'
    -
      x1: 0.4
      y1: 0.92
      label: 'Atlantic Ocean'
```
since the label and the variable name (e.g., g_of_mex) are kind of redundant here.
