### ISSUE TITLE
Move stream_params into viz_config?

### ISSUE THREAD

**Issue by jread-usgs** [USGS-VIZLAB/vizstorm-GIF#98]
Not sure if there are other yamls floating around in this repo, but this file only has 
```yaml
flow:
  - '00060'
stage:
  - '00065'
```
Move these into the config and remove this file?
